# Generated by Django 3.1.7 on 2021-09-09 21:24

from django.db import migrations, models
import test_app.test_organization.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "slug",
                    models.UUIDField(
                        blank=True, db_index=True, default=uuid.uuid4, editable=False
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Organization Name"),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("BA", "Bank"),
                            ("CU", "Credit Union"),
                            ("TH", "Thrift"),
                            ("QI", "Qualified Investor"),
                            ("OT", "Other"),
                        ],
                        default="BA",
                        max_length=2,
                        verbose_name="Organization Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address Line 1"
                    ),
                ),
                (
                    "street_address2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=200, verbose_name="City"),
                ),
                ("web", models.URLField(blank=True, verbose_name="Website URL")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lender",
                    models.BooleanField(
                        default=False, verbose_name="Organization is a Lender?"
                    ),
                ),
                (
                    "buyer",
                    models.BooleanField(
                        default=False, verbose_name="Organization is a loan buyer?"
                    ),
                ),
                (
                    "primary_contact_first_name",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="Primary Contact First Name",
                    ),
                ),
                (
                    "primary_contact_last_name",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="Primary Contact Last Name",
                    ),
                ),
                (
                    "primary_contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Primary Contact Email",
                    ),
                ),
                (
                    "primary_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Primary Contact Phone Number",
                    ),
                ),
                (
                    "primary_contact_cell_phone",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Primary Contact Cell Phone Number",
                    ),
                ),
                (
                    "primary_contact_title",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "require_two_factor",
                    models.BooleanField(
                        default=False, verbose_name="Require Two Factor Authentication"
                    ),
                ),
                (
                    "date_established",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Date Established"
                    ),
                ),
                (
                    "federal_reserve_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Federal Reserve ID"
                    ),
                ),
                (
                    "fdic_cert_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="FDIC Certificate Number"
                    ),
                ),
                (
                    "rating_agency",
                    models.CharField(
                        choices=[
                            ("FD", "FDIC"),
                            ("OC", "OCC"),
                            ("OT", "Other"),
                            ("NO", "None"),
                        ],
                        default="NO",
                        max_length=2,
                        verbose_name="Rating Agency",
                    ),
                ),
                (
                    "swift_bic",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="SWIFT/BIC"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=test_app.test_organization.models.public_organization_file_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "privacy_policy_url",
                    models.URLField(blank=True, verbose_name="Privacy Policy URL"),
                ),
                (
                    "terms_of_service_url",
                    models.URLField(blank=True, verbose_name="Terms of Service URL"),
                ),
                (
                    "enable_loan_mod_request_screen",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enable Loan Modification Request Screen",
                    ),
                ),
                (
                    "loan_mod_request_host_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="CNAME",
                    ),
                ),
                (
                    "custom_loan_mod_request_text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Custom text for loan modification public page",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "require_queue_user_membership",
                    models.BooleanField(
                        default=False,
                        help_text="This will restrict users from viewing this queue if they are not assigned to this queue specifically",
                        verbose_name="Require user to be specifically assigned to this queue in order to view tickets",
                    ),
                ),
                (
                    "custom_footer",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Custom footer for public pages",
                    ),
                ),
                (
                    "custom_email_text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Custom text for use in email templates",
                    ),
                ),
                (
                    "ppp_forgiveness_instructions",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="HTML for PPP Forgiveness Instructions Tab",
                    ),
                ),
                (
                    "docusign_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Docusign Enabled?"
                    ),
                ),
                (
                    "chatlio_enabled",
                    models.BooleanField(default=False, verbose_name="Chatlio Enabled?"),
                ),
                (
                    "session_timeout",
                    models.IntegerField(
                        default=3600, verbose_name="Session timeout (in seconds)"
                    ),
                ),
                (
                    "enable_2019_annual_revenue_input",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enable Borrower Input of 2020 Annual Revenue",
                    ),
                ),
                (
                    "get_started_background_image",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=test_app.test_organization.models.public_organization_file_path,
                        verbose_name="Image on Get Started Page",
                    ),
                ),
                (
                    "get_started_header_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Get Started Page Header Text",
                    ),
                ),
                (
                    "get_started_description_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Get Started Page Description Text",
                    ),
                ),
                (
                    "show_banker_contact_info",
                    models.BooleanField(
                        default=True,
                        verbose_name="Show Banker Contact Info to Borrower (when able)",
                    ),
                ),
                (
                    "sba_product_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SBA API Key",
                    ),
                ),
                ("forgiveness_enabled", models.BooleanField(default=True)),
                ("origination_enabled", models.BooleanField(default=False)),
                (
                    "origination_allow_banker_selection",
                    models.BooleanField(
                        default=True,
                        verbose_name="Origination - Allow Borrower to Select their Banker",
                    ),
                ),
                (
                    "origination_documents_required",
                    models.BooleanField(
                        default=True,
                        verbose_name="Origination - Borrower Supporting Documents are Required",
                    ),
                ),
                (
                    "day_count_method",
                    models.CharField(
                        choices=[
                            ("actual360", "Actual/360"),
                            ("actual365", "Actual/365"),
                            ("thirty360", "30/360"),
                        ],
                        default="actual360",
                        max_length=50,
                        verbose_name="Interest calculation method",
                    ),
                ),
                (
                    "sba_location_id",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="SBA Location ID",
                    ),
                ),
                (
                    "loan_number_assignment_strategy",
                    models.CharField(
                        choices=[
                            ("choose-from-pool", "Choose From Pool"),
                            ("defer-to-org", "Defer to Organization"),
                        ],
                        default="defer-to-org",
                        max_length=125,
                    ),
                ),
                (
                    "orig_only_existing_customers",
                    models.BooleanField(
                        default=False,
                        help_text="Only allows existing Bank customers to go through Origination",
                        verbose_name="Only Allow Existing Customers for Origination",
                    ),
                ),
                ("enable_wet_signature", models.BooleanField(default=False)),
                ("is_docusign_preview_enabled", models.BooleanField(default=False)),
                ("is_kyc_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
            },
        ),
    ]
