exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [.]

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --recursive,
            --remove-duplicate-keys,
            --remove-all-unused-imports,
            --remove-unused-variables,
            .,
          ]

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.0
  #   hooks:
  #     - id: bandit

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.2.2
  #   hooks:
  #   - id: python-safety-dependencies-check
  #     files: pyproject.toml


  #- repo: https://gitlab.com/pycqa/flake8
  #  rev: 3.9.2
  #  hooks:
  #    - id: flake8
  #      args: [--max-line-length=120]
  #      additional_dependencies: [flake8-isort]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
